/** @format */

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_PERSONS_SUCCESS = "GET_PERSONS_SUCCESS";
export const GET_PERSON_SUCCESS = "GET_PERSON_SUCCESS";
export const GET_PERSONS_FAIL = "GET_PERSONS_FAIL";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";
